import sortBy from "lodash/sortBy";

export const fakeArtists = sortBy([
  {
    name: "d",
    id: 248222,
    trackerText: "7,959 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/254324.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/254324.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/248222-d?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "D A",
    id: 3950493,
    trackerText: "55 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/06.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/05.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/3950493-d-a?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "A D",
    id: 3147194,
    trackerText: "92 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/06.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/02.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/3147194-a-d?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Drake",
    id: 1488,
    trackerText: "6,640,384 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/6527020.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/6527020.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/1488-drake?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "David Guetta",
    id: 26317,
    trackerText: "3,968,154 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/11035065.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/11035065.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/26317-david-guetta?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Demi Lovato",
    id: 22843,
    trackerText: "3,538,622 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/12533372.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/12533372.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/22843-demi-lovato?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Daft Punk",
    id: 263,
    trackerText: "2,992,904 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/226052.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/226052.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/263-daft-punk?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Disturbed",
    id: 68,
    trackerText: "2,537,375 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/8842395.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/8842395.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/68-disturbed?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },

  {
    name: "Tay",
    id: 73400,
    trackerText: "2,582 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/8445474.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/8445474.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/73400-tay?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "The Tay",
    id: 5419227,
    trackerText: "111 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/04.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/03.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/5419227-the-tay?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "T A Y",
    id: 647028,
    trackerText: "38 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/07.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/01.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/647028-t-a-y?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Taylor Swift",
    id: 157,
    trackerText: "7,251,771 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/11030358.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/11030358.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/157-taylor-swift?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Tay-K",
    id: 14753846,
    trackerText: "74,057 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/05.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/03.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/14753846-tay-k?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Taylor Henderson",
    id: 2652421,
    trackerText: "57,477 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/7311022.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/7311022.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/2652421-taylor-henderson?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Taylor Dayne",
    id: 8314,
    trackerText: "54,162 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/12647349.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/12647349.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/8314-taylor-dayne?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Taylor Bennett",
    id: 1928595,
    trackerText: "38,563 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/8452244.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/8452244.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/1928595-taylor-bennett?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Taylor Davis",
    id: 35669,
    trackerText: "33,908 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/8456317.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/8456317.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/35669-taylor-davis?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Taylor Ray Holbrook",
    id: 10402178,
    trackerText: "33,590 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/8288497.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/8288497.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/10402178-taylor-ray-holbrook?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },

  {
    name: "G",
    id: 44522,
    trackerText: "13,471 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/133211.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/133211.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/44522-g?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "G FoR",
    id: 11746094,
    trackerText: "39 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/03.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/05.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/11746094-g-for?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "la G",
    id: 8141309,
    trackerText: "55 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/01.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/08.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/8141309-la-g?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Green Day",
    id: 254,
    trackerText: "4,638,335 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/9373390.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/9373390.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/254-green-day?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Guns N' Roses",
    id: 145310,
    trackerText: "3,573,663 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/7979318.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/7979318.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/145310-guns-n'-roses?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "Gorillaz",
    id: 132,
    trackerText: "2,433,919 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/8988308.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/8988308.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/132-gorillaz?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "George Strait",
    id: 313,
    trackerText: "2,243,253 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/8984327.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/8984327.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/313-george-strait?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "G-Eazy",
    id: 211217,
    trackerText: "1,492,333 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/8282762.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/8282762.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/211217-g-eazy?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },

  {
    name: "?",
    id: 115167,
    trackerText: "4,986 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/191414.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/191414.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/115167-?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "?uestlove",
    id: 54692,
    trackerText: "16,310 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/08.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/03.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/54692-uestlove?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "? and the Mysterians",
    id: 48812,
    trackerText: "12,327 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/7855808.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/7855808.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/48812-and-the-mysterians?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "??",
    id: 671171,
    trackerText: "4,319 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/04.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/06.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/671171-?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "?AIMON",
    id: 1310931,
    trackerText: "3,912 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/9130213.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/9130213.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/1310931-aimon?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "???",
    id: 475896,
    trackerText: "3,477 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/6256531.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/6256531.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/475896-?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "????",
    id: 971219,
    trackerText: "2,725 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/08.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/05.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/971219-?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "?????",
    id: 5565486,
    trackerText: "2,613 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/10236357.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/10236357.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/5565486-?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "?????? ????????",
    id: 749056,
    trackerText: "1,477 Followers",
    imageSrc:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/05.png",
    properlySizedImageURL:
      "https://assets.prod.bandsintown.com/images/homeIcon/festivalPlaceHolderImage/01.webp",
    verifiedSrc: null,
    verified: false,
    href: "https://www.bandsintown.com/a/749056-?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
  {
    name: "??@$h",
    id: 15233,
    trackerText: "1,371 Followers",
    imageSrc: "https://photos.bandsintown.com/thumb/6046700.jpeg",
    properlySizedImageURL: "https://media.bandsintown.com/46x46/6046700.webp",
    verifiedSrc: "https://assets.prod.bandsintown.com/images/verifiedCheck.svg",
    verified: true,
    href: "https://www.bandsintown.com/a/15233-@dollarh?came_from=257&utm_medium=web&utm_source=home&utm_campaign=search_bar",
  },
]);
